---
stages: [sync]

mirror:
  stage: sync
  image: alpine:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success
    - when: never
  variables:
    GITLAB_PUSH_URL: "https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
  before_script:
    - apk add --no-cache git ca-certificates
    - git init --bare /tmp/mirror.git
    - cd /tmp/mirror.git
    - git remote add origin "$GITHUB_URL"
    - git remote add gitlab "$GITLAB_PUSH_URL"
  script:
    # fetch all branches & tags from GitHub
    - git fetch --prune --tags origin +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/*
    # drop remote-tracking refs so --mirror won't try to push them
    - git for-each-ref --format='%(refname)' refs/remotes | xargs -r -n1 git update-ref -d
    # mirror push (branches + tags; prunes deleted refs on target)
    - git push --prune --mirror gitlab
